name: tidy, test, coverage
on: [push, pull_request]
jobs:
#  tidy:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: 'recursive'
#      - uses: ./.github/actions/install-deps
#      - run: mkdir build
#      - run: cmake -B build -DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja
#      - run: find src -name '*.cpp' | xargs clang-tidy-13 -p build
  test-with-cov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-deps
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: "mycache"
      - name: set up ccache
        run: |
          mkdir -p ~/.ccache
          cp .github/workflows/ccache.conf ~/.ccache/ccache.conf
      - name: configure
        run: |
          mkdir build
          cmake -B build -DCMAKE_C_COMPILER=/usr/lib/ccache/clang-13 -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-13 -DSYSTEM_BOOST=FALSE -DSYSTEM_GRPC=FALSE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCOVERAGE=TRUE -GNinja
      - name: build
        run: ninja
        working-directory: ./build
      - name: test
        run: ninja test
        working-directory: ./build
      - name: coverage
        run: ninja coverage
        working-directory: ./build
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            build/coverage.txt
            build/coverage.html

        
